import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { client } from "../libs/client";
import { DiaryInfo } from "interfaces";

interface Props {
  diary?: Array<DiaryInfo>;
}

const Top: NextPage<Props> = ({ diary }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="diary">
        <ul className="diary-list">
          {diary?.map((d) => {
            return (
              <li key={d.id} className="diary-card">
                <h2 className="diary-title">{d.title}</h2>
                <p className="diary-when">
                  <span className="date">{d.date}</span>{" "}
                  <span className="day">{d.day}</span>
                </p>
                <img src={d.image.url} width="300" height="100%" />
                <div
                  className="news-detail_body"
                  dangerouslySetInnerHTML={{
                    __html: `${d.body}`,
                  }}
                />
              </li>
            );
          })}
        </ul>
      </div>
    </>
  );
};

export default Top;

export const getStaticProps: GetStaticProps = async () => {
  const data = await client.get({
    endpoint: "diary",
  });

  return {
    props: {
      diary: data.contents,
    },
  };
};
